# Things to make
fahrtocels: fahrtocels.c
	gcc -Wall -Wextra fahrtocels.c -o fahrtocels

celstofahr: celstofahr.c
	gcc -Wall -Wextra celstofahr.c -o celstofahr

intoout: intoout.c
	gcc -Wall -Wextra intoout.c -o intoout

numchars: num_chars.c
	gcc -Wall -Wextra num_chars.c -o numchars

countlines: countlines.c
	gcc -Wall -Wextra countlines.c -o countlines

countwhitespace: countwhitespace.c
	gcc -Wall -Wextra countwhitespace.c -o countwhitespace

singleblanks: singleblanks.c
	gcc -Wall -Wextra singleblanks.c -o singleblanks

escapewhitespace: escapewhitespace.c
	gcc -Wall -Wextra escapewhitespace.c -o escapewhitespace

wordcount: wordcount.c
	gcc -Wall -Wextra wordcount.c -o wordcount

printinput: printinput.c
	gcc -Wall -Wextra printinput.c -o printinput

countstuff: countstuff.c
	gcc -Wall -Wextra countstuff.c -o countstuff

wordlength: wordlength.c
	gcc -Wall -Wextra wordlength.c -o wordlength

charfreq: charfreq.c
	gcc -Wall -Wextra charfreq.c -o charfreq

longestline: longestline.c
	gcc -Wall -Wextra longestline.c -o longestline

printlonglines: printlonglines.c
	gcc -Wall -Wextra printlonglines.c -o printlonglines

trimwhitespace: trimwhitespace.c
	gcc -Wall -Wextra trimwhitespace.c -o trimwhitespace

reverselines: reverselines.c
	gcc -Wall -Wextra reverselines.c -o reverselines

tabtospace: tabtospace.c
	gcc -Wall -Wextra tabtospace.c -o tabtospace

spacetotab: spacetotab.c
	gcc -Wall -Wextra spacetotab.c -o spacetotab

wordwrap: wordwrap.c
	gcc -Wall -Wextra wordwrap.c -o wordwrap

removecomments: removecomments.c
	gcc -Wall -Wextra removecomments.c -o removecomments