keycount: keycount.c get_characters.c getword.c
	gcc -Wall -Wextra keycount.c get_characters.c getword.c -o keycount

wordfreq: wordfreq.c getword.c get_characters.c
	gcc -Wall -Wextra wordfreq.c getword.c get_characters.c -o wordfreq

variablenames: variablenames.c gettoken.c get_characters.c
	gcc -Wall -Wextra variablenames.c gettoken.c get_characters.c -o variablenames

wordsinlines: wordsinlines.c getword.c get_characters.c llist.c
	gcc -Wall -Wextra wordsinlines.c getword.c get_characters.c llist.c -o wordsinlines