calculator: main.c push_pop.c get_op.c get_characters.c
	gcc -Wall -Wextra main.c push_pop.c get_op.c get_characters.c -o calculator -lm

calculator4-8: main.c push_pop.c get_op.c get_chars_singlebuff.c
	gcc -Wall -Wextra main.c push_pop.c get_op.c get_chars_singlebuff.c -o calculator4-8 -lm